### ISSUE TITLE
unable to run npm from bootstrap due to missing dependencies

### ISSUE THREAD

**Issue by newbaluku** [devsapp/start-fc#13]
relating to sample: start-fc-custom-samples/nodejs12/event-demo

if I modify the package.json to add a startup script like this:
```
{
  "scripts": {
    "start": "node server.js"
  },
  "dependencies": {
    "express": "^4.17.1"
  }
}
```
and modify the bootstrap slightly as such:
```
#!/bin/bash
export PATH=/code/node-v12.13.0-linux-x64/bin:$PATH
node -v
# node server.js
npm start
```
invoking FC like so: s invoke -e "{}"
will get error:

![image](https://user-images.githubusercontent.com/13480257/151354928-32c0c995-f1e1-4a8b-a03a-c6d501a4de1f.png)

checking the Logstore shows that my FC custom runtime had crashed:

![image](https://user-images.githubusercontent.com/13480257/151354949-d75bf098-a060-4226-b8da-ca85b53bcf1e.png)

looks like some missing dependencies.

**Comment by rsonghuster** [comment]
https://github.com/devsapp/start-fc/tree/main/custom-function/nodejs12/fc-custom-nodejs12-event/src  is ok!
